dbfilename redis_queue.rdb
dir /home/beeyond/frappe-bench/beeyond/config/pids
pidfile /home/beeyond/frappe-bench/beeyond/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/beeyond/frappe-bench/beeyond/config/redis_queue.acl
